# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_strategy_class.o
obj-$(CONFIG_XM_POWER_SUPPLY)	+= strategy_charger/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= strategy_fg/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= strategy_pd/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= strategy_wireless/
