# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_XM_POWER_SUPPLY)	+= subpmic/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= charge_pump_ic/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= fuelgauge_ic/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= wireless_ic/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= boost_ic/
