# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_business_charger_comp.o
mca_business_charger_comp-objs	:= mca_business_charger.o mca_charger_usb_psy.o \
				   mca_charger_wireless_psy.o
