/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 The LineageOS Project
 *
 * Reporting charging faults.
 *
 * When something goes wrong while charging -- an adapter that fails to prove
 * itself, a charge pump that will not start, a cell taken out of range -- the
 * fault is worth recording with the values that explain it.  Each fault has a
 * code, a name, and the parameters it carries, so the record is the same
 * whichever driver noticed it.
 *
 * A fault that repeats would otherwise fill the log, so each is rate limited:
 * some are reported a fixed number of times per charger plugged in, and the
 * rest no more often than a stated interval.
 */

#ifndef __MCA_CHARGE_MIEVENT_H
#define __MCA_CHARGE_MIEVENT_H

/* What went wrong. */
enum charge_mievent_type_index {
	CHARGE_DFX_PD_AUTH_FAILED,
	CHARGE_DFX_CP_OPEN_FAILED,
	CHARGE_DFX_NOT_STANDARD_ADAPTER,
	CHARGE_DFX_RP_SHORT_VBUS_DETECTED,
	CHARGE_DFX_LPD_DETECTED,
	CHARGE_DFX_CP_VBUS_OVP,
	CHARGE_DFX_CP_IBUS_OCP,
	CHARGE_DFX_CP_VBAT_OVP,
	CHARGE_DFX_CP_IBAT_OCP,
	CHARGE_DFX_CP_VAC_OVP,
	CHARGE_DFX_ANTI_BURN_TRIGGERED,
	CHARGE_DFX_SOC_NOT_FULL,
	CHARGE_DFX_SMART_ENDURANCE_TRIGGERED,
	CHARGE_DFX_SMART_NAVIGATION_TRIGGERED,
	CHARGE_DFX_BATTERY_MISSING,
	CHARGE_DFX_CP_TDIE_HOT,
	CHARGE_DFX_VBUS_UVLO,
	CHARGE_DFX_LOW_TEMP_DISCHARGING,
	CHARGE_DFX_HIGH_TEMP_DISCHARGING,
	CHARGE_DFX_DUAL_BATTERY_MISSING,
	CHARGE_DFX_SMART_ENDURANCE_SOC_ERR,
	CHARGE_DFX_SMART_NAVIGATION_SOC_ERR,
	CHARGE_DFX_BATTERY_AUTH_FAIL,
	CHARGE_DFX_DUAL_BATTERY_AUTH_FAIL,
	CHARGE_DFX_ANTIBURN_ERR,
	CHARGE_DFX_WLS_FASTCHG_FAIL,
	CHARGE_DFX_WLS_FOD_LOW_POWER,
	CHARGE_DFX_WLS_RX_OTP,
	CHARGE_DFX_WLS_RX_OVP,
	CHARGE_DFX_WLS_RX_OCP,
	CHARGE_DFX_WLS_TRX_FOD,
	CHARGE_DFX_WLS_TRX_OCP,
	CHARGE_DFX_WLS_TRX_UVLO,
	CHARGE_DFX_WLS_TRX_IIC_ERR,
	CHARGE_DFX_WLS_RX_IIC_ERR,
	CHARGE_DFX_LOAD_SWITCH_I2C_ERR,
	CHARGE_DFX_WLS_FW_UPGRADE_FAIL,
	CHARGE_DFX_XMPPS_CHARGER_SLOWLY,
	CHARGE_DFX_NON_STANDARD_CHARGER,
	CHARGE_DFX_BATTERY_OCD,
	CHARGE_DFX_BATTERY_CUV,
	CHARGE_DFX_BATTERY_SCD,
	CHARGE_DFX_BATTERY_CYCLECOUNT,
	CHARGE_DFX_FG_IIC_ERR,
	CHARGE_DFX_CP_ABSENT,
	CHARGE_DFX_VBATT_SOC_NOT_MATCH,
	CHARGE_DFX_BATTERY_TEMP_HOT,
	CHARGE_DFX_BATTERY_TEMP_COLD,
	CHARGE_DFX_BATTERY_VOLTAGE_DIFFER,
	CHARGE_DFX_WLS_MAGNETIC_CASE_ATTACH,
	CHARGE_DFX_MAX_NUM,
};

/*
 * The code each fault is filed under.  Userspace groups faults by these
 * numbers rather than by name, so they are the interface and not an internal
 * ordering: the value matters, the position in the list does not.
 */
enum charge_mievent_type_num_ele {
	MIEVENT_CODE_PD_AUTH_FAILED = 909001004,
	MIEVENT_CODE_CP_OPEN_FAILED = 909001005,
	MIEVENT_CODE_XMPPS_CHARGER_SLOWLY = 909001006,
	MIEVENT_CODE_NON_STANDARD_CHARGER = 909001007,
	MIEVENT_CODE_NON_STANDARD_ADAPTER = 909002001,
	MIEVENT_CODE_RP_SHORT_VBUS_DETECTED = 909002002,
	MIEVENT_CODE_LPD_DETECTED = 909002003,
	MIEVENT_CODE_CP_VBUS_OVP = 909002004,
	MIEVENT_CODE_CP_IBUS_OCP = 909002005,
	MIEVENT_CODE_CP_VBAT_OVP = 909002006,
	MIEVENT_CODE_CP_IBAT_OCP = 909002007,
	MIEVENT_CODE_CP_VAC_OVP = 909002008,
	MIEVENT_CODE_ANTI_BURN_TRIGGERED = 909002012,
	MIEVENT_CODE_BATTERY_CYCLECOUNT = 909003001,
	MIEVENT_CODE_SOC_NOT_FULL = 909003002,
	MIEVENT_CODE_SMART_ENDURANCE_TRIGGERED = 909003004,
	MIEVENT_CODE_SMART_NAVIGATION_TRIGGERED = 909003006,
	MIEVENT_CODE_FG_IIC_ERR = 909005001,
	MIEVENT_CODE_CP_ABSENT = 909005002,
	MIEVENT_CODE_BATTERY_MISSING = 909005003,
	MIEVENT_CODE_CP_TDIE_HOT = 909005004,
	MIEVENT_CODE_VBUS_UVLO = 909005005,
	MIEVENT_CODE_LOW_TEMP_DISCHARGING = 909005007,
	MIEVENT_CODE_HIGH_TEMP_DISCHARGING = 909005008,
	MIEVENT_CODE_DUAL_BATTERY_MISSING = 909005009,
	MIEVENT_CODE_VBATT_SOC_NOT_MATCH = 909006001,
	MIEVENT_CODE_SMART_ENDURANCE_SOC_ERR = 909006010,
	MIEVENT_CODE_SMART_NAVIGATION_SOC_ERR = 909006011,
	MIEVENT_CODE_BATTERY_AUTH_FAIL = 909007001,
	MIEVENT_CODE_DUAL_BATTERY_AUTH_FAIL = 909007002,
	MIEVENT_CODE_LOAD_SWITCH_I2C_ERR = 909007003,
	MIEVENT_CODE_BATTERY_TEMP_HOT = 909009001,
	MIEVENT_CODE_BATTERY_TEMP_COLD = 909009002,
	MIEVENT_CODE_ANTIBURN_ERR = 909009003,
	MIEVENT_CODE_WLS_FASTCHG_FAIL = 909011001,
	MIEVENT_CODE_WLS_FOD_LOW_POWER = 909011002,
	MIEVENT_CODE_WLS_MAGNETIC_CASE_ATTACH = 909011003,
	MIEVENT_CODE_WLS_RX_OTP = 909012001,
	MIEVENT_CODE_WLS_RX_OVP = 909012002,
	MIEVENT_CODE_WLS_RX_OCP = 909012003,
	MIEVENT_CODE_WLS_TRX_FOD = 909012004,
	MIEVENT_CODE_WLS_TRX_OCP = 909012005,
	MIEVENT_CODE_WLS_TRX_UVLO = 909012006,
	MIEVENT_CODE_WLS_TRX_IIC_ERR = 909013001,
	MIEVENT_CODE_WLS_FW_UPGRADE_FAIL = 909013002,
	MIEVENT_CODE_WLS_RX_IIC_ERR = 909013004,
	MIEVENT_CODE_BATTERY_VOLTAGE_DIFFER = 909014002,
	MIEVENT_CODE_BATTERY_OCD = 909014003,
	MIEVENT_CODE_BATTERY_CUV = 909014004,
	MIEVENT_CODE_BATTERY_SCD = 909014005,
};

/* Whether the fault is reported per plug or on a timer. */
enum charge_mievent_upload_type_ele {
	MIEVENT_UPLOAD_TYPE_PLUG,
	MIEVENT_UPLOAD_TYPE_TIME,
	MIEVENT_UPLOAD_TYPE_MAX,
};

/* What the parameters that go with a fault are. */
enum charge_mievent_data_type_ele {
	MIEVENT_DATA_TYPE_INT,
	MIEVENT_DATA_TYPE_STRING,
	MIEVENT_DATA_TYPE_NULL,
	MIEVENT_DATA_TYPE_MAX,
};

/* What the caller is telling the reporter about. */
enum charge_mievent_state_ele {
	MIEVENT_STATE_PLUG,
	MIEVENT_STATE_END,
	MIEVENT_STATE_MAX,
};

void mca_charge_mievent_report(int event_index, void *data, int data_len);
void mca_charge_mievent_set_state(enum charge_mievent_state_ele state,
				  int value);

#endif /* __MCA_CHARGE_MIEVENT_H */
