/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 The LineageOS Project
 *
 * Talking to the ADSP about charging.
 *
 * Some of the charging hardware is not reached from the application
 * processor at all: the ADSP owns it, and the kernel asks the ADSP about it
 * over PMIC Glink.  Each exchange is a request naming a property and a
 * response carrying its value, matched by a sequence number so that a late
 * answer to an abandoned request is not mistaken for the answer to the
 * current one.
 *
 * The ADSP also volunteers notifications, and can restart underneath us, so
 * a caller registers for both.
 */

#ifndef __MCA_ADSP_GLINK_H
#define __MCA_ADSP_GLINK_H

#include <linux/types.h>

/* The most one property is allowed to carry. */
#define MCA_GLINK_DATA_MAX	256

/*
 * The properties the application processor can read from and write to the
 * charging firmware.  The firmware owns the charger; everything here is a
 * request to it or a question for it, and the numbering is the firmware's.
 *
 * The properties are grouped by what they concern.  Each group opens with an
 * identifier naming the group, which is not itself a property.
 */
enum mca_adsp_prop_id {
	/* Charging as a whole. */
	ADSP_PROP_ID_CHARGE_MISC_DOMAIN = 0,
	ADSP_PROP_ID_CHARGER_STATUS,
	ADSP_PROP_ID_OPERATIONAL_MODE,
	ADSP_PROP_ID_CHARGE_RATE,
	ADSP_PROP_ID_TEST_INFO,
	ADSP_PROP_ID_SHIP_MODE,
	ADSP_PROP_ID_SHUTDOWN_MODE,
	ADSP_PROP_ID_TOO_HOT_LIMIT,

	/* The wireless input. */
	ADSP_PROP_ID_CHARGR_DC_DOMAIN = 0x1000,
	ADSP_PROP_ID_DC_ONLINE,
	ADSP_PROP_ID_DC_RX_SLEEP,
	ADSP_PROP_ID_DC_INPUT_CURR_LIMIT,
	ADSP_PROP_ID_DC_INPUT_SUSPEND,
	ADSP_PROP_ID_DC_VOLTAGE_NOW,
	ADSP_PROP_ID_DC_VOLTAGE_MAX,
	ADSP_PROP_ID_DC_CURRENT_NOW,
	ADSP_PROP_ID_DC_CURRENT_MAX,
	ADSP_PROP_ID_DC_CHARGER_TYPE,
	ADSP_PROP_ID_DC_BOOST_EN,
	ADSP_PROP_ID_DC_HBST_VMAX,
	ADSP_PROP_ID_DC_SET_VDD_FLAG,

	/* The buck charger. */
	ADSP_PROP_ID_CHARGR_BUCK_DOMAIN = 0x2000,
	ADSP_PROP_ID_BUCK_CHGR_STATUS,
	ADSP_PROP_ID_BUCK_CHGR_TYPE,
	ADSP_PROP_ID_BUCK_ENABLE_CHARGING,
	ADSP_PROP_ID_BUCK_SET_FSW,
	ADSP_PROP_ID_BUCK_CHARGE_CURR,
	ADSP_PROP_ID_BUCK_TERM_CURR,
	ADSP_PROP_ID_BUCK_TERM_VOLT,
	ADSP_PROP_ID_BUCK_INPUT_CURR_LIMIT,
	ADSP_PROP_ID_BUCK_INPUT_VOLT_LIMIT,
	ADSP_PROP_ID_BUCK_PRECHG_CURR,
	ADSP_PROP_ID_BUCK_PRECHG_VOLT,
	ADSP_PROP_ID_BUCK_VSYSMIN,
	ADSP_PROP_ID_BUCK_OTG_BOOST_ENABLE_STATUS,
	ADSP_PROP_ID_BUCK_OTG_GATE_ENABLE_STATUS,
	ADSP_PROP_ID_BUCK_ENABLE_BOOST,
	ADSP_PROP_ID_BUCK_ADJUST_BOOST_VOLTAGE,
	ADSP_PROP_ID_BUCK_QC_VOLT,
	ADSP_PROP_ID_BUCK_ENABLE_AICL,
	ADSP_PROP_ID_BUCK_RERUN_AICL,
	ADSP_PROP_ID_BUCK_RESTART_AICL,
	ADSP_PROP_ID_BUCK_AICL_CONT_THD,
	ADSP_PROP_ID_BUCK_OPT_FWS,
	ADSP_PROP_ID_BUCK_USB_ADAPTER_ALLOW_OVERRIDE,
	ADSP_PROP_ID_BUCK_QC3_VOLT,
	ADSP_PROP_ID_BUCK_INPUT_SUSPEND,
	ADSP_PROP_ID_BUCK_OTG_CFG,
	ADSP_PROP_ID_BUCK_CID_CFG,
	ADSP_PROP_ID_BUCK_CP_STATE,
	ADSP_PROP_ID_BUCK_QC_VOLT_CMD,
	ADSP_PROP_ID_BUCK_LPD_SBU1,
	ADSP_PROP_ID_BUCK_LPD_SBU2,
	ADSP_PROP_ID_BUCK_LPD_CC1,
	ADSP_PROP_ID_BUCK_LPD_CC2,
	ADSP_PROP_ID_BUCK_LPD_DP,
	ADSP_PROP_ID_BUCK_LPD_DM,
	ADSP_PROP_ID_BUCK_LPD_CONTROL,
	ADSP_PROP_ID_BUCK_LPD_UART_CONTROL,
	ADSP_PROP_ID_BUCK_PACK_VBAT,
	ADSP_PROP_ID_BUCK_PACK_IBAT,
	ADSP_PROP_ID_BUCK_EU_MODEL,
	ADSP_PROP_ID_BUCK_AICL_STATUS,
	ADSP_PROP_ID_BUCK_PACK_TBAT,
	ADSP_PROP_ID_BUCK_OTG_CP_CFG_DONE,

	/* Which battery this is. */
	ADSP_PROP_ID_BATTERY_MISC_DOMAIN = 0x10000,
	ADSP_PROP_ID_BATT_ID,
	ADSP_PROP_ID_NOTIFICATION_CRITERIA,
	ADSP_PROP_ID_DISABLE_NOTIFICATION,
	ADSP_PROP_ID_BATTERY_INFORMATION,

	/* What the battery is doing. */
	ADSP_PROP_ID_BATTERY_INFO_DOMAIN = 0x11000,
	ADSP_PROP_ID_BATTERY_HEALTH,
	ADSP_PROP_ID_BATTERY_PRESENT,
	ADSP_PROP_ID_BATTERY_CHARGE_TYPE,
	ADSP_PROP_ID_BATTERY_CAPACITY,
	ADSP_PROP_ID_BATTERY_SOH,
	ADSP_PROP_ID_BATTERY_OCV,
	ADSP_PROP_ID_BATTERY_VOLTAGE_NOW,
	ADSP_PROP_ID_BATTERY_VOLTAGE_MAX,
	ADSP_PROP_ID_BATTERY_CURRENT_NOW,
	ADSP_PROP_ID_BATTERY_CHARGE_CONTROL_LIMIT,
	ADSP_PROP_ID_BATTERY_CHARGE_CONTROL_LIMIT_MAX,
	ADSP_PROP_ID_BATTERY_CONSTANT_CHARGE_CURRENT,
	ADSP_PROP_ID_BATTERY_BATTERY_TEMP,
	ADSP_PROP_ID_BATTERY_BATTERY_TECHNOLOGY,
	ADSP_PROP_ID_BATTERY_CHARGER_COUNTER,
	ADSP_PROP_ID_BATTERY_CYCLE_COUNTER,
	ADSP_PROP_ID_BATTERY_NOMINAL_CAPACITY,
	ADSP_PROP_ID_BATTERY_LEARNED_CAPACITY,
	ADSP_PROP_ID_BATTERY_BATTERY_MODEL,
	ADSP_PROP_ID_BATTERY_TTF,
	ADSP_PROP_ID_BATTERY_TTE,
	ADSP_PROP_ID_BATTERY_PROP_RESISTANCE,
	ADSP_PROP_ID_BATTERY_PROP_POWER_NOW,
	ADSP_PROP_ID_BATTERY_PROP_POWER_AVG,

	/* The USB input. */
	ADSP_PROP_ID_TYPEC_USB_DOMAIN = 0x20000,
	ADSP_PROP_ID_USB_ONLINE,
	ADSP_PROP_ID_USB_VOLTAGE_NOW,
	ADSP_PROP_ID_USB_SNS_VOLTAGE_NOW,
	ADSP_PROP_ID_USB_CURRENT_NOW,
	ADSP_PROP_ID_USB_CURRENT_MAX,
	ADSP_PROP_ID_USB_INPUT_CURRENT_LIMIT,
	ADSP_PROP_ID_USB_CHARGER_TYPE,
	ADSP_PROP_ID_USB_USB_TYPE,
	ADSP_PROP_ID_USB_MOISTURE_DETECTION_ENABLE,
	ADSP_PROP_ID_USB_MOISTURE_DETECTION_STATUS,
	ADSP_PROP_ID_USB_CONNECTOR_TEMP,
	ADSP_PROP_ID_USB_USB_REAL_TYPE,
	ADSP_PROP_ID_USB_USB_TYPEC_COMPLIANT,

	/* Power Delivery and the Type-C port. */
	ADSP_PROP_ID_TYPEC_PD_DOMAIN = 0x21000,
	ADSP_PROP_ID_TYPEC_SS_AUTH_DATA,
	ADSP_PROP_ID_TYPEC_VERIFY_PROCESS,
	ADSP_PROP_ID_TYPEC_VDM_CMD_CHARGER_VERSION,
	ADSP_PROP_ID_TYPEC_VDM_CMD_CHARGER_VOLTAGE,
	ADSP_PROP_ID_TYPEC_VDM_CMD_CHARGER_TEMP,
	ADSP_PROP_ID_TYPEC_VDM_CMD_SESSION_SEED,
	ADSP_PROP_ID_TYPEC_VDM_CMD_AUTHENTICATION,
	ADSP_PROP_ID_TYPEC_VDM_CMD_VERIFIED,
	ADSP_PROP_ID_TYPEC_VDM_CMD_REMOVE_COMPENSATION,
	ADSP_PROP_ID_TYPEC_VDM_CMD_REVERSE_AUTHEN,
	ADSP_PROP_ID_TYPEC_VDM_CMD_RESET_VSAFE0V,
	ADSP_PROP_ID_TYPEC_VDM_CMD_REQUEST_PD_DR,
	ADSP_PROP_ID_TYPEC_CURRENT_STATE,
	ADSP_PROP_ID_TYPEC_ADAPTER_ID,
	ADSP_PROP_ID_TYPEC_ADAPTER_SVID,
	ADSP_PROP_ID_TYPEC_PD_VERIFED,
	ADSP_PROP_ID_TYPEC_PDO,
	ADSP_PROP_ID_TYPEC_UVDM_STATE,
	ADSP_PROP_ID_TYPEC_PPS_ADV_CURRENT,
	ADSP_PROP_ID_TYPEC_PPS_APDO_MAX,
	ADSP_PROP_ID_TYPEC_TYPEC_MODE,
	ADSP_PROP_ID_TYPEC_CC_ORIENTATION,
	ADSP_PROP_ID_TYPEC_PPS_REQ,
	ADSP_PROP_ID_TYPEC_FIXED_VOL_REQ,
	ADSP_PROP_ID_TYPEC_PPS_STATUS,
	ADSP_PROP_ID_TYPEC_PD_MAX_VOLTAGE,
	ADSP_PROP_ID_TYPEC_PPS_POWER_MAX,
	ADSP_PROP_ID_TYPEC_PPS_MAX_VOLTAGE,
	ADSP_PROP_ID_TYPEC_MAX_VOLTAGE_SUPPORT,
	ADSP_PROP_ID_TYPEC_HAS_DP,
	ADSP_PROP_ID_TYPEC_CID_STATUS,
	ADSP_PROP_ID_TYPEC_OTG_PLUGIN_STATUS,
	ADSP_PROP_ID_TYPEC_CC_TOGGLE,
	ADSP_PROP_ID_TYPEC_SNK_SRC_MODE,
	ADSP_PROP_ID_TYPEC_CC_STATUS,
	ADSP_PROP_ID_TYPEC_CC_SHORT_VBUS,
	ADSP_PROP_ID_TYPEC_PPS_PTF,
	ADSP_PROP_ID_TYPEC_PD_SUSPEND_SUPPORT_STATUS,
	ADSP_PROP_ID_TYPEC_PPS_ZIMI_CYPRESS_FLAG,
	ADSP_PROP_ID_TYPEC_GEAR_SHIFT,
};

/*
 * What the firmware volunteers without being asked.  Each arrives with one
 * number whose meaning is the notification's own.
 */
enum mca_adsp_charger_notification {
	MCA_CHARGER_TYPE_CHANGE_NOTIFY,
	MCA_CHARGER_BATTERY_CHANGE_NOTIFY,
	MCA_CHARGER_ADT_CAP_CHANGE_NOTIFY,
	MCA_CHARGER_ENABLE_BOOST_NOTIFY,
	MCA_CHARGER_LPD_CHANGE_NOTIFY,
	MCA_CHARGER_TYPEC_CHANGE_NOTIFY,
	MCA_CHARGER_CC_SHORT_VBUS_NOTIFY,
	MCA_CHARGER_PPS_PTF_NOTIFY,
	MCA_CHARGER_SINK_PWR_SUSPEND_NOTIFY,
	MCA_CHARGER_QUICK_REVCHG_NOTIFY,
	MCA_CHARGER_OTG_CP_CONFIG_NOTIFY,
	MCA_CHARGER_CID_STS_NOTIFY,
};

/**
 * struct mca_adsp_call_back - what a caller wants to hear about
 * @glink_down_cb: the ADSP went away and what it was told is gone with it
 * @sync_data_cb:  the ADSP is back and wants to be told again
 * @notify_cb:     the ADSP has something to say
 */
struct mca_adsp_call_back {
	int (*glink_down_cb)(void *data);
	int (*sync_data_cb)(void *data);
	void (*notify_cb)(int notification, void *buf, int len, void *data);
};

int mca_adsp_glink_resister_ops(struct mca_adsp_call_back *cb, void *data);
int mca_adsp_glink_qbg_resister_ops(struct mca_adsp_call_back *cb, void *data);

int mca_adsp_glink_read_prop(u32 property_id, void *data, int len);
int mca_adsp_glink_write_prop(u32 property_id, void *data, int len);
int mca_adsp_glink_qbg_read_prop(u32 property_id, void *data, int len);
int mca_adsp_glink_qbg_write_prop(u32 property_id, void *data, int len);

#endif /* __MCA_ADSP_GLINK_H */
