# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_strategy_buckchg.o
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_strategy_quickchg.o
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_buckchg_jeita.o
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_charger_thermal.o
