# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_connector_antiburn.o
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_bmd.o
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_path_control.o
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_lpd_detect.o
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_vbat_ovp_monitor.o
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_ibat_ocp_monitor.o
